name: Publish to npm

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access=public
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{secrets.PERSONAL_TOKEN}}

